const questions = {
    normal: [
        "played hooky from school or work",
        "stolen anything",
        "missed a flight",
        "drunk-dialed my ex",
        "rode a motorcycle",
        "lost a bet",
        "gotten lost alone in a foreign country",
        "bribed someone",
        "gone skinny-dipping",
        "cheated on someone",
        "sang karaoke",
        "broken a bone",
        "lived alone",
        "been on a yacht",
        "been on TV",
        "been on a blind date",
        "lied to law enforcement",
        "gotten a tattoo",
        "used a fake ID",
        "broken up with someone",
        "got seriously hungover",
        "used someone else’s toothbrush",
        "clogged somebody else’s toilet",
        "fallen asleep in public",
        "kissed someone in public",
        "fought in public",
        "dined and dashed",
        "won the lottery",
        "had to go to court",
        "been to a destination wedding",
        "lied to a boss",
        "crashed a wedding",
        "kissed more than one person in 24 hours",
        "pranked someone",
        "had a one-night stand",
        "regifted a gift",
        "trolled someone on social media",
        "climbed out of a window",
        "driven over a curb",
        "laughed so hard I, um, peed my pants as an adult",
        "got on the wrong train or bus",
        "sent a sext",
        "cursed in a place of worship",
        "snooped through someone’s stuff",
        "tried marijuana",
        "gone 24 hours without showering",
        "had to take a walk of shame",
        "gone on a solo vacation",
        "gone on a road trip",
        "ate an entire pizza by myself",
        "saved a life",
        "got a tattoo",
        "wanted to be on a reality TV show",
        "started a fire",
        "gotten stopped by airport security",
        "gone viral online",
        "left gum in a public space",
        "slept outdoors for an entire night",
        "ran a marathon",
        "given/received a lap dance",
        "made a speech in front of 100 people or more",
        "relieved myself in a public pool",
        "lied to my best friend about who I was with",
        "been to a Disney park",
        "had a threesome",
        "left someone on read",
        "fallen asleep during sex",
        "lied about my age",
        "made up a story about someone who wasn’t real",
        "believed something was haunted",
        "participated in a protest",
        "had sleep paralysis",
        "been the alibi for a lying friend",
        "pulled an all-nighter",
        "role-played",
        "regretted an apology",
        "pretended I was sick for attention",
        "disliked something that I cooked",
        "deleted a post on social media because it didn’t get enough likes",
        "spent more than $100 on a top",
        "thrown a drink at someone",
        "worn someone else’s underwear",
        "traveled to Europe",
        "attempted a trendy diet",
        "gone to a strip club",
        "binged an entire series in one day",
        "tried psychedelics",
        "met someone famous",
        "gone streaking",
        "been on a sports team",
        "maxed out a credit card",
        "been blackout drunk",
        "been engaged",
        "gotten married",
        "donated to a charity",
        "pretended to be sick to get out of something",
        "stood up a date",
        "ghosted someone",
        "had sex on a beach",
        "fallen in love"
    ]
};
export default questions;
