const questions = {
    en: [
        "played hooky from school or work",
        "stolen anything",
        "missed a flight",
        "drunk-dialed my ex",
        "rode a motorcycle",
        "lost a bet",
        "gotten lost alone in a foreign country",
        "bribed someone",
        "gone skinny-dipping",
        "cheated on someone",
        "sang karaoke",
        "broken a bone",
        "lived alone",
        "been on a yacht",
        "been on TV",
        "been on a blind date",
        "lied to law enforcement",
        "gotten a tattoo",
        "used a fake ID",
        "broken up with someone",
        "got seriously hungover",
        "used someone else’s toothbrush",
        "clogged somebody else’s toilet",
        "fallen asleep in public",
        "kissed someone in public",
        "fought in public",
        "dined and dashed",
        "won the lottery",
        "had to go to court",
        "been to a destination wedding",
        "lied to a boss",
        "crashed a wedding",
        "kissed more than one person in 24 hours",
        "pranked someone",
        "had a one-night stand",
        "regifted a gift",
        "trolled someone on social media",
        "climbed out of a window",
        "driven over a curb",
        "laughed so hard I, um, peed my pants as an adult",
        "got on the wrong train or bus",
        "sent a sext",
        "cursed in a place of worship",
        "snooped through someone’s stuff",
        "tried marijuana",
        "gone 24 hours without showering",
        "had to take a walk of shame",
        "gone on a solo vacation",
        "gone on a road trip",
        "ate an entire pizza by myself",
        "saved a life",
        "got a tattoo",
        "wanted to be on a reality TV show",
        "started a fire",
        "gotten stopped by airport security",
        "gone viral online",
        "left gum in a public space",
        "slept outdoors for an entire night",
        "ran a marathon",
        "given/received a lap dance",
        "made a speech in front of 100 people or more",
        "relieved myself in a public pool",
        "lied to my best friend about who I was with",
        "been to a Disney park",
        "had a threesome",
        "left someone on read",
        "fallen asleep during sex",
        "lied about my age",
        "made up a story about someone who wasn’t real",
        "believed something was haunted",
        "participated in a protest",
        "had sleep paralysis",
        "been the alibi for a lying friend",
        "pulled an all-nighter",
        "role-played",
        "regretted an apology",
        "pretended I was sick for attention",
        "disliked something that I cooked",
        "deleted a post on social media because it didn’t get enough likes",
        "spent more than $100 on a top",
        "thrown a drink at someone",
        "worn someone else’s underwear",
        "traveled to Europe",
        "attempted a trendy diet",
        "gone to a strip club",
        "binged an entire series in one day",
        "tried psychedelics",
        "met someone famous",
        "gone streaking",
        "been on a sports team",
        "maxed out a credit card",
        "been blackout drunk",
        "been engaged",
        "gotten married",
        "donated to a charity",
        "pretended to be sick to get out of something",
        "stood up a date",
        "ghosted someone",
        "had sex on a beach",
        "fallen in love"
    ],
    hu: [
    "ettem ócska ételt.",
    "csesztem el valakinek a nyaralását.",
    "sírtam vagy könyörögtem, hogy szabaduljak meg a bírságtól vagy a büntetéstől.",
    "botlottam meg a mobilomra nézve.",
    "vágtam le a hajam, aztán megbántam.",
    "szerettem első látásra.",
    "mondtam valakinek, hogy \"szeretlek\", anélkül, hogy ezt jelenteném.",
    "hazudtam, hogy \"soha nem\" játszottam.",
    "voltam ébren két napja egymás után.",
    "festettem a hajam rikító vagy divatos színt.",
    "voltam ázsiai országban (megváltoztathatja a kontinenst).",
    "csináltam bungee jumpst.",
    "szerepeltem YouTube-videóban.",
    "vesztettem el az eszméletemet.",
    "késztettem valakit kórházba.",
    "veszítettem el az állásomat a bulizás és az előző este sok ivás miatt.",
    "dolgoztam részegen.",
    "mondtam, hogy nagyon tetszett egy ajándék, és akkor visszaadtam.",
    "volt paranormális tapasztalatom.",
    "voltam idegennel.",
    "használtam kábítószert.",
    "csináltam és nem is kaptam körtáncot.",
    "küldtem hangos vagy kirívó üzenetet rossz embernek.",
    "voltam bilincsben (bármilyen okból).",
    "éreztem a saját fehérneműm illatát, hogy megnézzem, tiszta-e vagy piszkos-e.",
    "loptam semmit egy boltból.",
    "játszottam otthon idegen fényekkel vagy a karácsonyfával a Stranger Things-t.",
    "csináltam Game of Thrones spoilert, akaratlanul vagy szándékosan.",
    "töröltem egy fotót a közösségi hálózattól, mert nem szeretem, hogyan jövök ki.",
    "hazudtam a barátaimnak.",
    "léptem be hívatlanul egy pártba.",
    "pofozkodtak a nyilvánosság előtt.",
    "gondoltam volna, hogy én vagyok a legszebb ember ebben a csoportban.",
    "hallgattam reggaetont a Spotify zártkörű ülésén, hogy senki ne fedezzen fel.",
    "volt vegetáriánus vagy vegán időm.",
    "mondtam rossz nevet szex közben.",
    "voltam senkivel a családomban.",
    "küldtem forró üzenetet rossz számra.",
    "szexeltem valakivel kétszer kétszer valakivel.",
    "gondoltam volna, hogy STD-m lehet.",
    "használtam közös tárgyat szexuális játékszerként, és visszatettem a webhelyére.",
    "volt hármasom.",
    "szexeltem több mint ötször egy éjszaka alatt.",
    "akartam kapcsolatba lépni azonos nemű emberrel.",
    "maszturbáltam a szabadban.",
    "mutattam meg magam webkamerán.",
    "voltam hűtlen.",
    "úsztam mezítelenül.",
    "kötöttem le egy barátom exét.",
    "jártam a volt párommal.",
    "voltam valakivel ebben a csoportban.",
    "sértettem meg magam, miközben megpróbáltam lenyűgözni egy érdeklődő lányt vagy fiút.",
    "hazudtam arról, hogy egy családtag ürügyként halt meg, hogy kiszálljon valami cselekedetről.",
    "töltöttem éjszakát erdőben menedék nélkül.",
    "tettem még soha szándékosan tüzet a hajamra vagy valaki másra.",
    "száguldottam át egy barátom fürdőszobájában vagy hálószobájában anélkül, hogy tudták volna.",
    "voltam még olyan kínos videóban, amelyet feltöltöttem a YouTube-ra.",
    "sírtam / flörtöltem ki a gyorshajtás jegyéből.",
    "vettem ki az ételeket a kukából, és nem ettem.",
    "sikoltozott senki velem egy munkámnál.",
    "sírtam nyilvánosan egy dal miatt.",
    "véletlenül mondtam valakinek „szeretlek”.",
    "nyomtam meg a küldést, és azonnal megbántam."
    ]
};
export default questions;
